import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',

    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            colors: {
                tertiary: '#f2cc00',
                primary: '#f1cc19',
                'on-secondary': '#313030',
                secondary: '#c8c6c5',
                'outline-variant': '#4d4635',
                'error-container': '#93000a',
                'on-secondary-fixed-variant': '#474746',
                'on-primary-fixed-variant': '#544600',
                'primary-fixed-dim': '#e8c408',
                'on-tertiary-fixed-variant': '#544600',
                'inverse-surface': '#e5e2e1',
                'on-primary': '#3a3000',
                surface: '#131313',
                'surface-dim': '#131313',
                'secondary-fixed': '#e5e2e1',
                'on-primary-fixed': '#221b00',
                'surface-bright': '#3a3939',
                'surface-container-high': '#2a2a2a',
                'on-primary-container': '#524400',
                'tertiary-fixed-dim': '#e9c400',
                'inverse-primary': '#705d00',
                'secondary-container': '#474746',
                'on-surface-variant': '#d0c5af',
                'on-background': '#e5e2e1',
                'tertiary-container': '#d2b100',
                background: '#131313',
                'surface-tint': '#e8c408',
                'surface-container-lowest': '#0e0e0e',
                'inverse-on-surface': '#313030',
                error: '#ffb4ab',
                'on-error': '#690005',
                'primary-fixed': '#ffe16c',
                'primary-container': '#d2b100',
                'on-tertiary': '#3a3000',
                'surface-variant': '#353534',
                'on-surface': '#e5e2e1',
                outline: '#99907c',
                'on-secondary-container': '#b7b5b4',
                'on-tertiary-container': '#534400',
                'on-secondary-fixed': '#1c1b1b',
                'on-tertiary-fixed': '#221b00',
                'secondary-fixed-dim': '#c8c6c5',
                'on-error-container': '#ffdad6',
                'tertiary-fixed': '#ffe16d',
                'surface-container': '#201f1f',
                'surface-container-highest': '#353534',
                'surface-container-low': '#1c1b1b',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
            fontFamily: {
                body: ['Inter', ...defaultTheme.fontFamily.sans],
                headline: ['Manrope', ...defaultTheme.fontFamily.sans],
                label: ['Inter', ...defaultTheme.fontFamily.sans],
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
            },
        },
    },

    plugins: [forms],
};
